apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/JaeBaeWon/K8S-manifest.git
    targetRevision: HEAD
    path: apps/backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
