apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spring-app-secret
  namespace: backend
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore   
  target:
    name: spring-app-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/backend
